const allCurrencies = [
  { name: "United Arab Emirates Dirham", code: "AED", zeroDecimal: false },
  { name: "Afghan Afghani", code: "AFN", zeroDecimal: false },
  { name: "Albanian Lek", code: "ALL", zeroDecimal: false },
  { name: "Armenian Dram", code: "AMD", zeroDecimal: false },
  { name: "Netherlands Antillean Guilder", code: "ANG", zeroDecimal: false },
  { name: "Angolan Kwanza", code: "AOA", zeroDecimal: false },
  { name: "Argentine Peso", code: "ARS", zeroDecimal: false },
  { name: "Australian Dollar", code: "AUD", zeroDecimal: false },
  { name: "Aruban Florin", code: "AWG", zeroDecimal: false },
  { name: "Azerbaijani Manat", code: "AZN", zeroDecimal: false },
  {
    name: "Bosnia-Herzegovina Convertible Mark",
    code: "BAM",
    zeroDecimal: false,
  },
  { name: "Barbadian Dollar", code: "BBD", zeroDecimal: false },
  { name: "Bangladeshi Taka", code: "BDT", zeroDecimal: false },
  { name: "Bulgarian Lev", code: "BGN", zeroDecimal: false },
  { name: "Bahraini Dinar", code: "BHD", zeroDecimal: false },
  { name: "Burundian Franc", code: "BIF", zeroDecimal: true },
  { name: "Bermudan Dollar", code: "BMD", zeroDecimal: false },
  { name: "Brunei Dollar", code: "BND", zeroDecimal: false },
  { name: "Bolivian Boliviano", code: "BOB", zeroDecimal: false },
  { name: "Brazilian Real", code: "BRL", zeroDecimal: false },
  { name: "Bahamian Dollar", code: "BSD", zeroDecimal: false },
  { name: "Bitcoin", code: "BTC", zeroDecimal: false },
  { name: "Bhutanese Ngultrum", code: "BTN", zeroDecimal: false },
  { name: "Botswanan Pula", code: "BWP", zeroDecimal: false },
  { name: "Belarusian Ruble", code: "BYN", zeroDecimal: false },
  { name: "Belize Dollar", code: "BZD", zeroDecimal: false },
  { name: "Canadian Dollar", code: "CAD", zeroDecimal: false },
  { name: "Congolese Franc", code: "CDF", zeroDecimal: false },
  { name: "Swiss Franc", code: "CHF", zeroDecimal: false },
  { name: "Chilean Unit of Account (UF)", code: "CLF", zeroDecimal: false },
  { name: "Chilean Peso", code: "CLP", zeroDecimal: true },
  { name: "Chinese Yuan (Offshore)", code: "CNH", zeroDecimal: false },
  { name: "Chinese Yuan", code: "CNY", zeroDecimal: false },
  { name: "Colombian Peso", code: "COP", zeroDecimal: false },
  { name: "Costa Rican Colón", code: "CRC", zeroDecimal: false },
  { name: "Cuban Convertible Peso", code: "CUC", zeroDecimal: false },
  { name: "Cuban Peso", code: "CUP", zeroDecimal: false },
  { name: "Cape Verdean Escudo", code: "CVE", zeroDecimal: false },
  { name: "Czech Republic Koruna", code: "CZK", zeroDecimal: false },
  { name: "Djiboutian Franc", code: "DJF", zeroDecimal: true },
  { name: "Danish Krone", code: "DKK", zeroDecimal: false },
  { name: "Dominican Peso", code: "DOP", zeroDecimal: false },
  { name: "Algerian Dinar", code: "DZD", zeroDecimal: false },
  { name: "Egyptian Pound", code: "EGP", zeroDecimal: false },
  { name: "Eritrean Nakfa", code: "ERN", zeroDecimal: false },
  { name: "Ethiopian Birr", code: "ETB", zeroDecimal: false },
  { name: "Euro", code: "EUR", zeroDecimal: false },
  { name: "Fijian Dollar", code: "FJD", zeroDecimal: false },
  { name: "Falkland Islands Pound", code: "FKP", zeroDecimal: false },
  { name: "British Pound Sterling", code: "GBP", zeroDecimal: false },
  { name: "Georgian Lari", code: "GEL", zeroDecimal: false },
  { name: "Guernsey Pound", code: "GGP", zeroDecimal: false },
  { name: "Ghanaian Cedi", code: "GHS", zeroDecimal: false },
  { name: "Gibraltar Pound", code: "GIP", zeroDecimal: false },
  { name: "Gambian Dalasi", code: "GMD", zeroDecimal: false },
  { name: "Guinean Franc", code: "GNF", zeroDecimal: true },
  { name: "Guatemalan Quetzal", code: "GTQ", zeroDecimal: false },
  { name: "Guyanaese Dollar", code: "GYD", zeroDecimal: false },
  { name: "Hong Kong Dollar", code: "HKD", zeroDecimal: false },
  { name: "Honduran Lempira", code: "HNL", zeroDecimal: false },
  { name: "Croatian Kuna", code: "HRK", zeroDecimal: false },
  { name: "Haitian Gourde", code: "HTG", zeroDecimal: false },
  { name: "Hungarian Forint", code: "HUF", zeroDecimal: false },
  { name: "Indonesian Rupiah", code: "IDR", zeroDecimal: false },
  { name: "Israeli New Sheqel", code: "ILS", zeroDecimal: false },
  { name: "Manx pound", code: "IMP", zeroDecimal: false },
  { name: "Indian Rupee", code: "INR", zeroDecimal: false },
  { name: "Iraqi Dinar", code: "IQD", zeroDecimal: false },
  { name: "Iranian Rial", code: "IRR", zeroDecimal: false },
  { name: "Icelandic Króna", code: "ISK", zeroDecimal: false },
  { name: "Jersey Pound", code: "JEP", zeroDecimal: false },
  { name: "Jamaican Dollar", code: "JMD", zeroDecimal: false },
  { name: "Jordanian Dinar", code: "JOD", zeroDecimal: false },
  { name: "Japanese Yen", code: "JPY", zeroDecimal: true },
  { name: "Kenyan Shilling", code: "KES", zeroDecimal: false },
  { name: "Kyrgystani Som", code: "KGS", zeroDecimal: false },
  { name: "Cambodian Riel", code: "KHR", zeroDecimal: false },
  { name: "Comorian Franc", code: "KMF", zeroDecimal: true },
  { name: "North Korean Won", code: "KPW", zeroDecimal: false },
  { name: "South Korean Won", code: "KRW", zeroDecimal: true },
  { name: "Kuwaiti Dinar", code: "KWD", zeroDecimal: false },
  { name: "Cayman Islands Dollar", code: "KYD", zeroDecimal: false },
  { name: "Kazakhstani Tenge", code: "KZT", zeroDecimal: false },
  { name: "Laotian Kip", code: "LAK", zeroDecimal: false },
  { name: "Lebanese Pound", code: "LBP", zeroDecimal: false },
  { name: "Sri Lankan Rupee", code: "LKR", zeroDecimal: false },
  { name: "Liberian Dollar", code: "LRD", zeroDecimal: false },
  { name: "Lesotho Loti", code: "LSL", zeroDecimal: false },
  { name: "Libyan Dinar", code: "LYD", zeroDecimal: false },
  { name: "Moroccan Dirham", code: "MAD", zeroDecimal: false },
  { name: "Moldovan Leu", code: "MDL", zeroDecimal: false },
  { name: "Malagasy Ariary", code: "MGA", zeroDecimal: true },
  { name: "Macedonian Denar", code: "MKD", zeroDecimal: false },
  { name: "Myanma Kyat", code: "MMK", zeroDecimal: false },
  { name: "Mongolian Tugrik", code: "MNT", zeroDecimal: false },
  { name: "Macanese Pataca", code: "MOP", zeroDecimal: false },
  { name: "Mauritanian Ouguiya (pre-2018)", code: "MRO", zeroDecimal: false },
  { name: "Mauritanian Ouguiya", code: "MRU", zeroDecimal: false },
  { name: "Mauritian Rupee", code: "MUR", zeroDecimal: false },
  { name: "Maldivian Rufiyaa", code: "MVR", zeroDecimal: false },
  { name: "Malawian Kwacha", code: "MWK", zeroDecimal: false },
  { name: "Mexican Peso", code: "MXN", zeroDecimal: false },
  { name: "Malaysian Ringgit", code: "MYR", zeroDecimal: false },
  { name: "Mozambican Metical", code: "MZN", zeroDecimal: false },
  { name: "Namibian Dollar", code: "NAD", zeroDecimal: false },
  { name: "Nigerian Naira", code: "NGN", zeroDecimal: false },
  { name: "Nicaraguan Córdoba", code: "NIO", zeroDecimal: false },
  { name: "Norwegian Krone", code: "NOK", zeroDecimal: false },
  { name: "Nepalese Rupee", code: "NPR", zeroDecimal: false },
  { name: "New Zealand Dollar", code: "NZD", zeroDecimal: false },
  { name: "Omani Rial", code: "OMR", zeroDecimal: false },
  { name: "Panamanian Balboa", code: "PAB", zeroDecimal: false },
  { name: "Peruvian Nuevo Sol", code: "PEN", zeroDecimal: false },
  { name: "Papua New Guinean Kina", code: "PGK", zeroDecimal: false },
  { name: "Philippine Peso", code: "PHP", zeroDecimal: false },
  { name: "Pakistani Rupee", code: "PKR", zeroDecimal: false },
  { name: "Polish Zloty", code: "PLN", zeroDecimal: false },
  { name: "Paraguayan Guarani", code: "PYG", zeroDecimal: true },
  { name: "Qatari Rial", code: "QAR", zeroDecimal: false },
  { name: "Romanian Leu", code: "RON", zeroDecimal: false },
  { name: "Serbian Dinar", code: "RSD", zeroDecimal: false },
  { name: "Russian Ruble", code: "RUB", zeroDecimal: false },
  { name: "Rwandan Franc", code: "RWF", zeroDecimal: true },
  { name: "Saudi Riyal", code: "SAR", zeroDecimal: false },
  { name: "Solomon Islands Dollar", code: "SBD", zeroDecimal: false },
  { name: "Seychellois Rupee", code: "SCR", zeroDecimal: false },
  { name: "Sudanese Pound", code: "SDG", zeroDecimal: false },
  { name: "Swedish Krona", code: "SEK", zeroDecimal: false },
  { name: "Singapore Dollar", code: "SGD", zeroDecimal: false },
  { name: "Saint Helena Pound", code: "SHP", zeroDecimal: false },
  { name: "Sierra Leonean Leone", code: "SLL", zeroDecimal: false },
  { name: "Somali Shilling", code: "SOS", zeroDecimal: false },
  { name: "Surinamese Dollar", code: "SRD", zeroDecimal: false },
  { name: "South Sudanese Pound", code: "SSP", zeroDecimal: false },
  {
    name: "São Tomé and Príncipe Dobra (pre-2018)",
    code: "STD",
    zeroDecimal: false,
  },
  { name: "São Tomé and Príncipe Dobra", code: "STN", zeroDecimal: false },
  { name: "Salvadoran Colón", code: "SVC", zeroDecimal: false },
  { name: "Syrian Pound", code: "SYP", zeroDecimal: false },
  { name: "Swazi Lilangeni", code: "SZL", zeroDecimal: false },
  { name: "Thai Baht", code: "THB", zeroDecimal: false },
  { name: "Tajikistani Somoni", code: "TJS", zeroDecimal: false },
  { name: "Turkmenistani Manat", code: "TMT", zeroDecimal: false },
  { name: "Tunisian Dinar", code: "TND", zeroDecimal: false },
  { name: "Tongan Pa'anga", code: "TOP", zeroDecimal: false },
  { name: "Turkish Lira", code: "TRY", zeroDecimal: false },
  { name: "Trinidad and Tobago Dollar", code: "TTD", zeroDecimal: false },
  { name: "New Taiwan Dollar", code: "TWD", zeroDecimal: false },
  { name: "Tanzanian Shilling", code: "TZS", zeroDecimal: false },
  { name: "Ukrainian Hryvnia", code: "UAH", zeroDecimal: false },
  { name: "Ugandan Shilling", code: "UGX", zeroDecimal: true },
  { name: "United States Dollar", code: "USD", zeroDecimal: false },
  { name: "Uruguayan Peso", code: "UYU", zeroDecimal: false },
  { name: "Uzbekistan Som", code: "UZS", zeroDecimal: false },
  { name: "Venezuelan Bolívar Fuerte (Old)", code: "VEF", zeroDecimal: false },
  { name: "Venezuelan Bolívar Soberano", code: "VES", zeroDecimal: false },
  { name: "Vietnamese Dong", code: "VND", zeroDecimal: true },
  { name: "Vanuatu Vatu", code: "VUV", zeroDecimal: true },
  { name: "Samoan Tala", code: "WST", zeroDecimal: false },
  { name: "CFA Franc BEAC", code: "XAF", zeroDecimal: true },
  { name: "Silver Ounce", code: "XAG", zeroDecimal: false },
  { name: "Gold Ounce", code: "XAU", zeroDecimal: false },
  { name: "East Caribbean Dollar", code: "XCD", zeroDecimal: false },
  { name: "Special Drawing Rights", code: "XDR", zeroDecimal: false },
  { name: "CFA Franc BCEAO", code: "XOF", zeroDecimal: true },
  { name: "Palladium Ounce", code: "XPD", zeroDecimal: false },
  { name: "CFP Franc", code: "XPF", zeroDecimal: true },
  { name: "Platinum Ounce", code: "XPT", zeroDecimal: false },
  { name: "Yemeni Rial", code: "YER", zeroDecimal: false },
  { name: "South African Rand", code: "ZAR", zeroDecimal: false },
  { name: "Zambian Kwacha", code: "ZMW", zeroDecimal: false },
  { name: "Zimbabwean Dollar", code: "ZWL", zeroDecimal: false },
];
